---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-aap-operator
policyDefaults:
  namespace: policies
  namespaceSelector:
    include:
    - aap
  placement:
    clusterSelectors:
      local-cluster: "true"
  remediationAction: enforce
policies:
  - name: aap-operator-install
    manifests:
      - path: ns.yaml
      - path: operatorGroup.yaml
      - path: subscription.yaml
