---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:subscription-admin
  annotations:
    argocd.argoproj.io/sync-wave: "55"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kube:admin
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:admin
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: cluster-admin
