---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rhacm-policies
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "102"
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - rhacm-policies
