---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: default
  name: global
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  clusterSet: global
