---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-rhacs-central
policyDefaults:
  namespace: policies
  namespaceSelector:
    include:
    - rhacs-operator
  placement:
    clusterSelectors:
      local-cluster: "true"
  remediationAction: enforce
policies:
  - name: rhacs-central-install
    manifests:
      - path: central.yaml
      - path: jobInit.yaml
      - path: jobAuthProvider.yaml
      - path: rbac
