---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm/policies
    apps.open-cluster-management.io/reconcile-option: merge
    argocd.argoproj.io/sync-wave: "101"
  labels:
    app: rhacm-policies
  name: rhacm-policies-subscription-1
  namespace: default
spec:
  channel: ggithubcom-lpanza-ocp4-acm-acs-aap-day1-ns/ggithubcom-lpanza-ocp4-acm-acs-aap-day1
  placement:
    placementRef:
      kind: Placement
      name: rhacm-policies-placement-1
